name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Updated to 24 to stop the warning
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Lint
        run: npm run lint

      - name: Build TypeScript
        run: npm run build

      - name: Run Tests
        # We add this flag to handle ES Modules correctly in CI
        run: NODE_OPTIONS=--experimental-vm-modules npm test